# **ASSIGMENT-1**

**........................................................**

***NAME   : MAYALURI ANUSHA***

***REG.NO : 21BCE9143***

***BRANCH : CSE with Spec in AIML***

***CAMPUS : VIT-AP***

***EVENING BATCH : 6:00pm-8:00pm***

**........................................................**

## SET -1 QUESTIONS

Task -1 : Create a pandas dataframe (Dataframe name as 'df') with numpy random values (4 features and 4 observations)

In [ ]:
import pandas as pd
import numpy as np
data = np.random.rand(4, 4)
df = pd.DataFrame(data)
print(df)

          0         1         2         3
0  0.032586  0.261040  0.179379  0.590779
1  0.633512  0.568964  0.585747  0.764526
2  0.513459  0.057182  0.901075  0.467890
3  0.663713  0.038807  0.938267  0.627429

Task -2 : Rename the task-1 'df' dataframe column names to 'Random value 1', 'Random value 2', 'Random value 3' & 'Random value 4'

In [ ]:
df.columns=['Random value 1','Random value 2','Random value 3','Random value 4']
print(df)

   Random value 1  Random value 2  Random value 3  Random value 4
0        0.032586        0.261040        0.179379        0.590779
1        0.633512        0.568964        0.585747        0.764526
2        0.513459        0.057182        0.901075        0.467890
3        0.663713        0.038807        0.938267        0.627429

Task -3 : Find the descriptive statistics of the 'df' dataframe.

In [ ]:
df.describe()

       Random value 1  Random value 2  Random value 3  Random value 4
count        4.000000        4.000000        4.000000        4.000000
mean         0.460818        0.231498        0.651117        0.612656
std          0.292770        0.246490        0.352015        0.122091
min          0.032586        0.038807        0.179379        0.467890
25%          0.393241        0.052588        0.484155        0.560057
50%          0.573486        0.159111        0.743411        0.609104
75%          0.641062        0.338021        0.910373        0.661703
max          0.663713        0.568964        0.938267        0.764526

Task -4 : Check for the null values in 'df' and find the data type of the columns.

In [ ]:
df.isnull()

   Random value 1  Random value 2  Random value 3  Random value 4
0           False           False           False           False
1           False           False           False           False
2           False           False           False           False
3           False           False           False           False

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Random value 1  4 non-null      float64
 1   Random value 2  4 non-null      float64
 2   Random value 3  4 non-null      float64
 3   Random value 4  4 non-null      float64
dtypes: float64(4)
memory usage: 256.0 bytes

Task -5 : Display the 'Random value 2' & 'Random value 3' columns with location method and index location method.

In [ ]:
df.loc[:,'Random value 2':'Random value 3']

   Random value 2  Random value 3
0        0.261040        0.179379
1        0.568964        0.585747
2        0.057182        0.901075
3        0.038807        0.938267

In [ ]:
df.iloc[:,1:3]

   Random value 2  Random value 3
0        0.261040        0.179379
1        0.568964        0.585747
2        0.057182        0.901075
3        0.038807        0.938267

***....THANK YOU....***